Creating quicksort algorithm in kin lang
kin-lang/algorithms pull request #1
Opened 2024-05-16 09:50 UTC by MicoDan

This is the implementation of the quick sort algorithm in the kin lang programming language

2024-05-16 12:33 UTC, pacifiquem requested changes
Change file name to `quick.kin` to maintain the early format for this repo

2024-05-16 12:42 UTC, pacifiquem requested changes

2024-05-16 12:42 UTC, pacifiquem commented on src/sorting/quicksort
When tested on these dataset: `[45, 11, 56, 2, 0, 12, 155, 3, 3, 4, 566]`
This was the output:
```txt
45
11
56
2
0
12
155
3
3
4
566
```

2024-05-16 12:51 UTC, MicoDan commented
I don't know if it's an error on your end but the algorithm works perfect for me locally, even testing with that same dataset,
<img width="907" alt="test" src="https://github.com/kin-lang/algorithms/assets/121478029/420ab75b-8565-45ee-837c-9ab49ad919e3">
 take a look:

2024-05-16 12:57 UTC, pacifiquem commented
Not sure what's wrong with kin-lang/kin#117 this PR is good to be merged.

2024-05-16 13:02 UTC, pacifiquem approved these changes

2024-05-16 13:03 UTC, pacifiquem commented
This PR will remain open until further testcases on kin-lang/kin#117 are finished. Thanks @MicoDan

2024-05-17 05:21 UTC, pacifiquem approved these changes

2024-05-18 08:41 UTC, pacifiquem commented
With issue (kin-lang/kin#119) fixed in [v0.3.1-beta](https://github.com/kin-lang/kin/releases/tag/v0.3.1-beta)

This PR passes all checks, thanks for contributions @MicoDan .

2024-05-18 08:42 UTC, merged